### ISSUE TITLE
Does not follow reroutes when buckets are in a different region

### ISSUE THREAD

**Issue by kmader** [twpayne/s3-parallel-put#17]
The script didnt work with a bucket I have in the eu-west-1 region and gave the error ```error: [Errno 104] Connection reset by peer``` adding  ```--host=s3-eu-west-1.amazonaws.com``` seemed to make it work again

**Comment by mikeatlas** [comment]
https://github.com/twpayne/s3-parallel-put/issues/21 author doesn't understand this.

**Comment by mikeatlas** [comment]
See https://github.com/twpayne/s3-parallel-put/pull/23 - tiny change to support buckets in other regions.

**Comment by mikeatlas** [comment]
^ Updated

**Comment by twpayne** [comment]
Fixed by @mikeatlas in #24. Please re-open if this does not work for you.
