### ISSUE TITLE
socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by alkemrebecca** [twpayne/s3-parallel-put#21]
installed: python 2.7.6, boto

i am having this error:

Traceback (most recent call last):
  File "/s3-parallel-put", line 410, in <module>
    sys.exit(main(sys.argv))
  File "/s3-parallel-put", line 381, in main
    bucket = connection.get_bucket(options.bucket)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 503, in get_bucket
    return self.head_bucket(bucket_name, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 522, in head_bucket
    response = self.make_request('HEAD', bucket_name, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 665, in make_request
    retry_handler=retry_handler
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1030, in _mexe
    raise ex
socket.gaierror: [Errno -2] Name or service not known

May i know how to resolve it?
Thanks.

**Comment by twpayne** [comment]
I am not in a position to provide technical support for s3-parallel-put.

**Comment by mikeatlas** [comment]
Is that a joke reply @twpayne ?  Please re-open; I have the same problem, my bucket happens to not reside in US-Standard, most likely you simply need to support the bucket's region if you're using `boto` under the hood.

**Comment by mikeatlas** [comment]
Perhaps author means they don't have time to support their code anymore. Which is why forking is great.

https://github.com/weftio/s3-parallel-put/blob/d0aaf13e1ec9213877679c08813469b1678353d7/s3-parallel-put#L382 

Here's a quick change I made to support my bucket in `us-west-2` region @alkemrebecca, feel free to use that script instead and make changes to your bucket's region.

I personally don't work much with Python and have little interest or time myself in creating a proper fork, library, wrapper, or supporting this (awesomely powerful) library just so that it can handle buckets in another region correctly and easily, but I'm probably not the first fork to do so on what appears to be abandonware (and mostly uncommented abandonware).

Here's to hoping someone else comes along and fixes it up the right way.

**Comment by mikeatlas** [comment]
PR ^ above to support fixing this issue.

**Comment by alkemrebecca** [comment]
Hi mlkeatlas,
thanks so much. It seems to work.
May I know if I am able to update to a specific folder in s3?
It seems like for the current it uploads the same folder structure as the origin.

**Comment by mikeatlas** [comment]
I'm sure it's possible, but for me this was a 1-time task, so I just set my personal `s3-parallel-put` source path to mimic the structure of the bucket keys I wanted on s3:

`python s3-parallel-put --bucket=weft-wind-data --secure --put=update --processes=50 --content-type=guess --verbose --log-filename=/tmp/s3pp.log /your/local/ec2/path` 

where every directory and file in `/your/local/ec2/path` gets mimicked into the bucket path.

I challenge you to find out this parameter on the command line and figure out how the tool creates bucket paths that mirror the local file system, and then maybe you find a way to add a new bucket path prefix to upload to. (Although... isn't there a "prefix" parameter here?" Either way, I don't have additional time to help customize and support this script right now.

**Comment by mikeatlas** [comment]
Yeah, you should be able to just use `--prefix=PREFIX` for specific bucket prefix key (technically there are no folders in s3, just a bucket + bucketKey. The bucketKey includes the path and file name all-in-one.

**Comment by alkemrebecca** [comment]
Hi mlkeatlas, i've tested --prefix and it seems like there is no response to the parameter.

I realised that it uploads as standard.
May I also know if it is possible to upload as reduced redundancy instead?

**Comment by mikeatlas** [comment]
@alkemrebecca again this is not my library to support, please consider if you need to extend functionality that you make an effort to debug and make PRs yourself. Or read the documentation of S3 and this script:

> `--header=HEADER:VALUE` adds an arbitrary header to the S3 file. This option can be specified multiple times.`

See: http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html

> To store an object using reduced redundancy, set the `x-amz-storage-class` request header to `REDUCED_REDUNDANCY`.

How about you try: `--header=x-amz-storage-class:REDUCED_REDUNDANCY` with this script, see if it works?

**Comment by alkemrebecca** [comment]
Hi mlkeatlas, the reduced redundancy works!
Thanks so much!
Guess I just have to figure out the folder part.

**Comment by mikeatlas** [comment]
Lucky you :) You're welcome :) The "folder" part you must remember is that on s3, there is only "Bucket Name" and "Bucket Key". There concept of "folders" is simply bucket keys with (`/slashes/in/the/keys/file/name`).

**Comment by alkemrebecca** [comment]
Sure. I will take note of that.
Thanks soooo much!

**Comment by alkemrebecca** [comment]
Hi mlkeatlas, just to share with you and the others who are looking for the same.
I've figured how to do the folder part.
I have created the exact directory which I wanted in s3 and created a symbolic link to the original folder.
This way, when running the script, it will follow the path which I indicated. =)

Though i spotted that the final child files do not follow the permission that is set while indicating the command. Might want to upload to another folder and change the permission first before moving to the actual folder.

**Comment by twpayne** [comment]
I wrote `s3-parallel-put` for a project I was working on three years ago, and have not used it since. If someone would like to take over maintainership then I would be very happy - I can add you as a contributor here so you can push and merge pull requests.

**Comment by mikeatlas** [comment]
@twpayne Appreciate the offer and I wish I had a reason to maintain it myself. Alas, I'm not a daily Pythonista, nor do I have daily needs to s3-parallel-put, but so long as you're willing to accept PRs from time to time, that's good enough for most of us.

**Comment by mikeatlas** [comment]
Some kind of test suite an probably a pip package would be nice, but I don't really even know what goes into making those. Most of my time are in ruby/node/angular projects these days (gems, npm and bower) with a sprinkling of Clojure/Java (maven)...
