### ISSUE TITLE
`content-type` should default to guess

### ISSUE THREAD

**Issue by adamlwgriffiths** [twpayne/s3-parallel-put#30]
By now, I've accidentally uploaded multiple days worth of data to S3, only to find it unusable due to the content-type being `application/octet-stream`. This renders images, html, css, etc, unusable by default.

The default logic should be safe to use and therefore: the default content-type option should be `guess`.

This will need to take into account the gzip options logic to ensure it doesn't break gzip when no content-type is specified.

**Comment by schmoove** [comment]
+1 I've just arrived at the same problem

@adamlwgriffiths how did you resolve this? Reupload with content-type set? Ideally I'd prefer to not reupload days worth of data.

**Comment by adamlwgriffiths** [comment]
I had to re-upload the files with --content-type=<type here>.
Luckily the files were all the same.
An easier way would be to write a script to traverse the bucket and modify the meta data values, but it was easier to start a re-upload in the background than to spend the time writing said script.
