### ISSUE TITLE
ERROR:s3-parallel-put:missing source operand

### ISSUE THREAD

**Issue by dfriestedt** [twpayne/s3-parallel-put#31]
I'm getting the follow error when I execute the following command:

 /home/user/s3-parallel-put-master/s3-parallel-put --bucket=photos --put=stupid --insecure --dry-run --limit=1 

ERROR:s3-parallel-put:missing source operand

what am I missing?

**Comment by twpayne** [comment]
You need to supply the names of the files you want to upload.

**Comment by dfriestedt** [comment]
My folder has millions of files.  Do I need to upload the directory instead?  Or can I upload the contents of the folder with a wildcard?  If so, what command do I use?

thx

**Comment by twpayne** [comment]
You can pass either the directory name or just `.` if you're already in the right directory. Using `--dry-run` (as you do) is a good idea for testing!
